### PR TITLE
Support pattern start with character class

### PR DESCRIPTION
**Pull request by okkez**
See #58

### CODE REVIEW

**Comment by okkez** [comment]
@y-ken Could you review this change?

**Comment by repeatedly** [comment]
Maybe, need to update README "why `/pattern/` is preferred" with examples.

**Comment by y-ken** [comment]
Umm, It sounds common problems when using regexp.
Do you have any option to set none array parameter for `pattern`?

**Comment by okkez** [comment]
We can write both of following:

Starting with character classes:
```
<rule>
  key message
  pattern /[a-z]+/
  tag ...
</rule>
```

Not stating with character classes:
```
<rule>
  key message
  pattern agent[1-9][0-9]?
  tag ...
</rule>
```

Still cause error:
```
<rule>
  key message
  pattern [0-9][1-9]+
  tag ...
</rule>
```

**Comment by y-ken** [comment]
Hi @okkez
It sounds good to have slash in README example.
As like those, Would you please update up-to-date configuration style?
https://github.com/fluent/fluent-plugin-rewrite-tag-filter/blob/master/example.conf
https://github.com/fluent/fluent-plugin-rewrite-tag-filter/blob/master/example2.conf

**Comment by okkez** [comment]
OK, I will create new PR to update examples.

**Pull request merged**
