### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
Merge this PR after merge #29 and release new version.

**Comment by cosmo0920** [comment]
We should bump up major version to support newly added v0.14 APIs in fluentd plugins.
In this case, we should use version `2.0.0` instead of `1.5.6`.

**Comment by okkez** [comment]
Thank you for comment. I pushed changes.

**Comment by repeatedly** [comment]
ping?

**Comment by ryan-dyer-sp** [comment]
Can we get an update on this?  Any reason this hasn't been merged?

**Comment by okkez** [comment]
Do you have any concern? @y-ken

**Comment by y-ken** [comment]
@okkez 
For final release for v0.12 api, I'd like to support label and some compatible improvements.
For example, support label feature and add some code such as `require "fluent/plugin/output`.

**Comment by okkez** [comment]
@y-ken 
Nothing to do for v0.12 final release.
Label feature is already supported.
Additional code such as `require "fluent/plugin/output"` is not useful. Because this plugin's gemspec includes `s.add_runtime_dependency "fluentd", [">= 0.10.0", "< 0.14.0"]`. This means fluent-plugin-rewrite-tag-filter 1.5.6 does not support Fluentd v0.14 or later.
If you want to use fluent-plugin-rewrite-tag-filter 1.5.x with Fluentd v0.14.x, you need additional code such as `require "fluent/plugin/output"` to use compatibility layer.

**Comment by PatrikCyvoct** [comment]
Hello :)
Any news on the PR ?

**Comment by Globegitter** [comment]
Yeah would be great to finally get this out for 0.14 :)

**Comment by matikij** [comment]
bump :-)

**Comment by y-ken** [comment]
OK! It's time to release!

**Comment by y-ken** [comment]
I'm worried about auto upgrade to fluentd v0.14.x for fluentd v0.12.x users.
To prevent auto upgrading, Adding version suffix like `2.0.0.pre`.
Do you mind if I add version suffix?

**Comment by okkez** [comment]
It's nice idea adding suffix to prevent auto upgrade for v0.12.x users.
FYI: other plugins add version suffix `.rc1`, `rc2`,....

**Comment by y-ken** [comment]
OK! I'll use the rc1

**Comment by repeatedly** [comment]
y-ken is hard to take time for release management.
So adding new one active maintainer is good for this plugin.

**Comment by cosmo0920** [comment]
I think that one of the suitable active maintainer candidate is @okkez!

**Comment by okkez** [comment]
OK. I want to take over release management.
Please give me a commit privilege of this repository and add me to owner of this gem.

**Comment by repeatedly** [comment]
@y-ken If you okay, could you add okkez to new maintainer?
`rewrite-tag-filter` plugin is widely used so delaying release affect many users.

**Comment by repeatedly** [comment]
@okkez I added you to maintainers.
What the email do you use in rubygems?

**Comment by okkez** [comment]
@repeatedly  My email address is `okkez000 at gmail.com`.

**Comment by repeatedly** [comment]
Just added

**Comment by okkez** [comment]
Thanks!

**Comment by okkez** [comment]
Released [v2.0.0.rc1](https://rubygems.org/gems/fluent-plugin-rewrite-tag-filter/versions/2.0.0.rc1)

**Pull request merged**
