### PR TITLE
Update example

### LINKED ISSUE #65: Update configuration examples to latest configuration syntax
Was reviewing example.conf and example2.conf but they seem to use the legacy configuration style. Please provide examples using the new configuration style which has rule elements instead of manually named rewriterule_N_

### PR DESCRIPTION
**Pull request by okkez**
* Stop using fluent-plugin-forest
* Use `<rule>` section instead of `rewriterule<N>`
* Use `<parse>` section instead of `format` parameter
* Use `@type` parameter instead of `type` parameter

Close #65

### CODE REVIEW

**Comment by y-ken** [comment]
Wow, I have just noticed the way to replace forest in this case.
Does it keep same tag routing pipeline?

**Comment by okkez** [comment]
Maybe yes. But I could not test the configuration totally. Because I don't have proper logs for the example configuration.

I tested a simple case.
The tag transition is following(example.conf):

1. input tag is td.apache.access
1. Rewrite tags as following
  * site.GoogleMaps
  * site.GoogleNews
  * site.GoogleMail
1. Second level analyzing
  * site.GoogleMaps.Labs, site.GoogleMaps.Static, site.GoogleMaps.Help, ...
1. Summarize
  * site.GoogleMaps.Labs -> gf.responsetime.site.GoogleMaps.Labs
  * site.GoogleMaps.Labs -> gf.responsecode.site.GoogleMaps.Labs
  * site.GoogleMaps.Labs -> gf.useragent.site.GoogleMaps.Labs
1. Graph
  * keep same tag

**Comment by y-ken** [comment]
Cool!

**Comment by okkez** [comment]
Thank you for merging!

**Pull request merged**
