### PR TITLE
Support nested attributes

### LINKED ISSUE #13: Impossible to use nested attributes
Unless there's some specific syntax that I missed finding in the documentation, the plugin does not work with an `<attribute>` that is not a flat, first-level one.

For example, the following rule (written for an event in which the `geoip` object contains various data such as `country`, `region`, `latitude`, etc...)  fails to execute correctly:

```
<match geoip.** >
  type               rewrite_tag_filter
  rewriterule1       geoip.country SWE lookup.${tag}
  rewriterule2       geoip.country [^SWE] ready.${tag}
</match>
```

Resulting in the entire entry being lost.  Am I doing something wrong?

### PR DESCRIPTION
**Pull request by okkez**
Close #13

### CODE REVIEW

**Comment by y-ken** [comment]
It seems nice! Would you please add a sample for README?

**Comment by okkez** [comment]
OK, I will add sample to README in next week.

**Comment by okkez** [comment]
@y-ken  I've added sample to README.
Could you review again?

**Comment by y-ken** [comment]
Excellent!
kubernetes convination example is best for this!

**Comment by y-ken** [comment]
And,, Could you add for v0.12?

**Comment by okkez** [comment]
We can add rule section to v0.12 but we can not add nested attribute to v0.12.
Because record accessor plugin helper is not supported in Fluentd v0.12.
On the other hand, section notation is supported since Fluentd v0.12.

Should I backport nested attributes?
We can process nested attribute with filter_record_transformer for Fluentd v0.12.
https://github.com/fluent/fluent-plugin-rewrite-tag-filter/issues/13#issuecomment-278576763

**Comment by y-ken** [comment]
I understand. It is not good approach to add nested attribute,
Could you add note at README for nested attribute workaround with Fluentd v0.12

**Comment by okkez** [comment]
OK, I will add workaround to README on fluentd-v0.12 branch.

**Comment by y-ken** [comment]
Thank you very much!

**Comment by y-ken** [comment]
It is ok to show as the link.

**Pull request merged**
