### PR TITLE
Add descriptions for parameters

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by y-ken** [comment]
Hi @okkez 
Nice, Thank you!
Would you like to release new version of gem?

**Comment by okkez** [comment]
@y-ken Yes, I want to new version of gem.
Thank you for merging this PR :smile:

**Comment by y-ken** [comment]
It has released now!
https://rubygems.org/gems/fluent-plugin-rewrite-tag-filter/versions/1.5.4

**Comment by okkez** [comment]
Thank you!

**Pull request merged**
