### PR TITLE
Specify supported Fluentd version explicitly

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
And I will migrate this plugin to v0.14 API soon in another PR.

**Comment by y-ken** [comment]
@okkez 
Is it the time to release rewrite-tag-filter for fluentd v0.12?

**Comment by okkez** [comment]
Yes, release new version for Fluentd v0.12, please.

**Comment by y-ken** [comment]
I have released fluent-plugin-rewrite-tag-filter (1.5.6) now!

**Comment by okkez** [comment]
Thank you for new release :100:

**Pull request merged**
