### PR TITLE
Use router.emit instead of Fluent::Engine.emit

### PR DESCRIPTION
**Pull request by cosmo0920**

### CODE REVIEW

**Comment by y-ken** [comment]
Hi. Would you please support backward compatibility like this?
https://github.com/y-ken/fluent-plugin-twitter/pull/15

**Comment by cosmo0920** [comment]
Thanks.
I modified this PR to keep backward compatibility.

**Comment by y-ken** [comment]
Thanks!

**Comment by cosmo0920** [comment]
Thanks!!

**Pull request merged**
