### PR TITLE
Support rule section

### LINKED ISSUE #41: Support section notation
How about section notation like this?

```
<match **>
  @type rewrite_tag_filter
  <rule>
    key domain
    pattern ^(mail)\.(example)\.com$
    tag rewrited.${tag}.$2$1
  </rule>
</match>
```

### PR DESCRIPTION
**Pull request by okkez**
Close #41

### CODE REVIEW

**Comment by okkez** [comment]
@y-ken Can I drop old line style support for rewrite-tag-filter 2.0.0? and deprecation warning for rewrite-tag-filter 1.x ?

**Comment by okkez** [comment]
CI failed against c968d4e and b16acb9 are not reproducible in my local environment.

**Comment by y-ken** [comment]
> Can I drop old line style support for rewrite-tag-filter 2.0.0? and deprecation warning for rewrite-tag-filter 1.x ?


Yes. It makes much clear the difference for new and old style.

**Comment by y-ken** [comment]
It gets better and better. Thank you!
For adding `<rule>` section is very nice because fluentd v0.14 introducing section so much such as `<buffer>` section.

**Pull request merged**
